Repository Fool-Stuck/wheel_stuck_ws, pull requests merged in 2024-07, with the labels that each got.

#74 doc: create LICENSE
  LICENSE
Labels: documentation

#86 feat(planning): create waypoint system package directories
  .github/CODEOWNERS
  src/planning/waypoint/wheel_stuck_waypoint_msgs/CMakeLists.txt
  src/planning/waypoint/wheel_stuck_waypoint_msgs/msg/Route.msg
  src/planning/waypoint/wheel_stuck_waypoint_msgs/msg/Waypoint.msg
  src/planning/waypoint/wheel_stuck_waypoint_msgs/msg/WaypointAttribute.msg
  src/planning/waypoint/wheel_stuck_waypoint_msgs/package.xml
  src/planning/waypoint/wheel_stuck_waypoint_utils/CMakeLists.txt
  src/planning/waypoint/wheel_stuck_waypoint_utils/include/wheel_stuck_waypoint_utils/.gitkeep
  src/planning/waypoint/wheel_stuck_waypoint_utils/package.xml
  src/planning/waypoint/wheel_stuck_waypoint_utils/test/test_wheel_stuck_waypoint_utils.cpp
Labels: new feature

#94 hotfix(planning): add license notation to test_wheel_stuck_waypoint_utils.cpp
  src/planning/waypoint/wheel_stuck_waypoint_utils/test/test_wheel_stuck_waypoint_utils.cpp
Labels: chore task

#101 chore(common): change utils package name from wheel_stuck_utils to wheel_stuck_common_utils
  .github/CODEOWNERS
  src/common/wheel_stuck_common_utils/CMakeLists.txt
  src/common/wheel_stuck_common_utils/include/wheel_stuck_common_utils/math/math.hpp
  src/common/wheel_stuck_common_utils/include/wheel_stuck_common_utils/ros/function_timer.hpp
  src/common/wheel_stuck_common_utils/include/wheel_stuck_common_utils/ros/no_callback_subscription.hpp
  src/common/wheel_stuck_common_utils/package.xml
  src/common/wheel_stuck_common_utils/test/math/test_clamp01.cpp
  src/common/wheel_stuck_common_utils/test/math/test_inverse_lerp.cpp
  src/common/wheel_stuck_common_utils/test/math/test_lerp.cpp
  src/common/wheel_stuck_common_utils/test/math/test_max.cpp
  src/common/wheel_stuck_common_utils/test/math/test_min.cpp
  src/common/wheel_stuck_common_utils/test/math/test_sign.cpp
  src/common/wheel_stuck_common_utils/test/test_wheel_stuck_common_utils.cpp
  src/perception/velodyne_cloud_separator/include/velodyne_cloud_separator/velodyne_cloud_separator.hpp
  src/perception/velodyne_cloud_separator/package.xml
  src/planning/dwa_planner/include/dwa_planner/dwa_planner.hpp
  src/planning/dwa_planner/package.xml
  src/planning/dwa_planner/src/dwa_planner.cpp
  src/sample/simple_int_publisher/include/simple_int_publisher/simple_int_publisher.hpp
  src/sample/simple_int_publisher/package.xml
  src/sample/simple_int_subscriber/include/simple_int_subscriber/polling_int_subscriber.hpp
  src/sample/simple_int_subscriber/package.xml
Labels: chore task, high priority

#95 ci: create build-and-test-differential.yaml
  .github/workflows/build-and-test-differential.yaml
  .github/workflows/build-and-test.yaml
Labels: high priority

#93 chore: remove legal/copyright filter from CPPLINT.cfg
  CPPLINT.cfg
Labels: chore task

#104 chore: changed to use FunctionTimer as update timer for dwa_planner
  src/planning/dwa_planner/include/dwa_planner/dwa_planner.hpp
  src/planning/dwa_planner/src/dwa_planner.cpp
Labels: enhancement, chore task

#103 chore: changed to use FunctionTimer as update timer for velodyne_cloud_separator.
  src/perception/velodyne_cloud_separator/include/velodyne_cloud_separator/velodyne_cloud_separator.hpp
  src/perception/velodyne_cloud_separator/src/velodyne_cloud_separator.cpp
Labels: enhancement, chore task

#100 Update README.md
  README.md
Labels: documentation, chore task
